name: sql-generate-report
run-name: SQL Generate Report ${{ github.event.inputs.sql-environment }}. Job ${{ github.job }} started by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      sql-environment:
        type: environment
        description: Select the environment
      sql-query:
        description: "SQL Query to Execute"
        required: true
        type: string

jobs:
  sql-generate-report:
    name: Run SQL Statements
    runs-on: commonservices-${{ github.event.inputs.sql-environment }}
    environment: ${{ github.event.inputs.sql-environment }}

    steps:
      - name: Check-out repo to GitHub
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.role_arn }}
          role-external-id: ${{ secrets.external_id }}
          role-skip-session-tagging: true

      - name: Get Timestamp
        env:
          TZ: Asia/Singapore
        run: echo "TIMESTAMP=$(date +%d%m%y-%H%M)" >> $GITHUB_ENV

      - name: Execute MySQL query
        run: |
          DB_SERVER_ENDPOINT=$(aws rds describe-db-cluster-endpoints --db-cluster-identifier ciam-${{ github.event.inputs.sql-environment }} --query 'DBClusterEndpoints[*].[Endpoint]' --filters 'Name=db-cluster-endpoint-type,Values=writer' --output text)
          DB_USERNAME=$(aws secretsmanager get-secret-value --secret-id ciam-${{ github.event.inputs.sql-environment }}-db-user1 --query 'SecretString' --output text|jq -r .db_user)
          DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ciam-${{ github.event.inputs.sql-environment }}-db-user1 --query 'SecretString' --output text|jq -r .db_password)
          mkdir -p ./reports
          mysql -h $DB_SERVER_ENDPOINT -P 3306 --ssl -u $DB_USERNAME -p$DB_PASSWORD -D ciam -e "${{ github.event.inputs.sql-query }}" | sed "s/\t/,/g" > ./reports/query-results-${{env.TIMESTAMP}}.csv

      - name: Generate Report
        uses: actions/upload-artifact@v4
        with:
          name: query-results-${{env.TIMESTAMP}}
          path: ./reports/query-results-*.csv
          retention-days: 60

      - name: Verify all reports generated
        run: |
          if [ ! -s ./reports/query-results-${{ env.TIMESTAMP }}.csv ]; then
            echo "Warning: The query returned no results"
            exit 1
          fi

